DELIMITER //
CREATE TRIGGER update_stock_before_order
BEFORE INSERT ON detalle_pedido
FOR EACH ROW
BEGIN
    UPDATE productos
    SET CANTIDAD_PRODUCTO = CANTIDAD_PRODUCTO - NEW.CANTIDAD
    WHERE IDPRODUCTO = NEW.IDPRODUCTO;
END;
//
DELIMITER ;


DELIMITER //
CREATE TRIGGER reduce_stock_after_order
AFTER INSERT ON pedidos
FOR EACH ROW
BEGIN

END;
//
DELIMITER ;
